x-healthcheck: &healthcheck
  interval: 5s
  timeout: 5s
  retries: 3

services:
  wp:
    image: wordpress:6.9-php${PHP_VERSION:-8.4}-apache
    depends_on:
      db:
        condition: service_healthy
    ports:
      - ${FORWARD_WEB_PORT:-8080}:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASS}
      WORDPRESS_DB_NAME: ${DB_NAME}
    volumes:
      - ./docker/volumes/wordpress:/var/www/html
      - ./packages/custom-theme:/var/www/html/wp-content/themes/custom-theme
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      <<: *healthcheck

  cli:
    image: wordpress:cli-php${PHP_VERSION:-8.4}
    command: ["/bin/bash", "/usr/local/bin/init-wp"]
    user: '33'
    depends_on:
      db:
        condition: service_healthy
      wp:
        condition: service_healthy
    environment:
      SITE_URL: ${SITE_URL:-http://localhost:${FORWARD_WEB_PORT:-8080}}
      SITE_TITLE: ${SITE_TITLE:-"WordPress Local"}
      SITE_ADMIN_USER: ${SITE_ADMIN_USER}
      SITE_ADMIN_PASS: ${SITE_ADMIN_PASS}
      SITE_ADMIN_EMAIL: ${SITE_ADMIN_EMAIL}
      SITE_PLUGINS: ${SITE_PLUGINS:-}
      SITE_THEMES: ${SITE_THEMES:-}
      SITE_DEFAULT_THEME: ${SITE_DEFAULT_THEME:-}
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASS}
      WORDPRESS_DB_NAME: ${DB_NAME}
    volumes:
      - ./docker/volumes/wordpress:/var/www/html
      - ./packages/custom-theme:/var/www/html/wp-content/themes/custom-theme:ro
      - ./docker/init-wp.sh:/usr/local/bin/init-wp:ro

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./docker/volumes/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      <<: *healthcheck

networks:
  default:
     name: wordpress
