x-healthcheck: &healthcheck
  interval: 5s
  timeout: 5s
  retries: 3

x-wp-envs: &wp-envs
  WORDPRESS_DB_HOST: db
  WORDPRESS_DB_USER: ${DB_USER:-wordpress}
  WORDPRESS_DB_PASSWORD: ${DB_PASS:-secret}
  WORDPRESS_DB_NAME: ${DB_NAME:-wordpress}

services:
  wp:
    image: wordpress:6.9-php${PHP_VERSION:-8.4}-apache
    depends_on:
      db:
        condition: service_healthy
    ports:
      - ${FORWARD_WEB_PORT:-8080}:80
    environment:
      <<: *wp-envs
    volumes:
      - ./docker/volumes/wordpress:/var/www/html
      - ./packages/custom-theme:/var/www/html/wp-content/themes/custom-theme
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      <<: *healthcheck

  cli:
    image: wordpress:cli-php${PHP_VERSION:-8.4}
    command: ["/bin/bash", "/usr/local/bin/init-wp"]
    depends_on:
      db:
        condition: service_healthy
      wp:
        condition: service_healthy
    environment:
      <<: *wp-envs
      SITE_URL: ${SITE_URL:-http://localhost:${FORWARD_WEB_PORT:-8080}}
      SITE_TITLE: ${SITE_TITLE:-"WordPress Local"}
      SITE_TIMEZONE: ${SITE_TIMEZONE:-"Asia/Jakarta"}
      SITE_ADMIN_USER: ${SITE_ADMIN_USER:-local-admin}
      SITE_ADMIN_PASS: ${SITE_ADMIN_PASS:-secret}
      SITE_ADMIN_EMAIL: ${SITE_ADMIN_EMAIL:-admin@example.com}
      SITE_PLUGINS: ${SITE_PLUGINS:-}
      SITE_THEMES: ${SITE_THEMES:-}
      SITE_DEFAULT_THEME: ${SITE_DEFAULT_THEME:-}
      MULTISITE_ENABLED: ${MULTISITE_ENABLED:-0}
    volumes:
      - ./docker/volumes/wordpress:/var/www/html
      - ./public:/var/www/public
      - ./packages/custom-theme:/var/www/html/wp-content/themes/custom-theme:ro
      - ./docker/init-wp.sh:/usr/local/bin/init-wp:ro

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_NAME:-wordpress}
      MYSQL_USER: ${DB_USER:-wordpress}
      MYSQL_PASSWORD: ${DB_PASS:-secret}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./docker/volumes/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      <<: *healthcheck

networks:
  default:
     name: wordpress
